---
- name: Install dependencies
  apt:
    name: ["libssl-dev", "libreadline-dev", "zlib1g-dev", "libsqlite3-dev"]
    state: latest
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  become: true
