- name: Install application specific dependencies
  apt:
    name: ["imagemagick", "libvips-tools"]
    state: latest
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'
  become: true
