---
- name: Check for rbenv installation
  stat:
    path: "{{ rbenv_path }}"
  register: rbenv
  ignore_errors: true

- block:
    - name: Download and install rbenv
      shell:
        warn: false
        cmd: |
          wget -q "{{rbenv_installer_url}}" -O- | bash
          echo 'export PATH="{{rbenv_path}}/bin:$PATH"' >> /home/vagrant/.bashrc
          echo 'export PATH="{{rbenv_path}}/shims:$PATH"' >> /home/vagrant/.bashrc
          echo 'eval "$(rbenv init -)"' >> /home/vagrant/.bashrc
          touch /home/vagrant/.gemrc
          echo 'gem: --no-document' >> /home/vagrant/.gemrc

  when: rbenv.stat.exists == false
